service: cart-service
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
